// SPDX-License-Identifier: Apache-2.0

// Command compatibility publishes a deterministic snapshot of the frontend
// validator registries. It neither renders manifests nor starts the runtime.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/albertize/grillo/internal/frontend/compose"
	"github.com/albertize/grillo/internal/frontend/kubernetes"
	"github.com/albertize/grillo/internal/source"
)

func entries() []source.RegisteredFeature {
	all := append(compose.SupportEntries(), kubernetes.SupportEntries()...)
	sort.Slice(all, func(i, j int) bool {
		a, b := all[i], all[j]
		if a.Format != b.Format {
			return a.Format < b.Format
		}
		if a.Scope != b.Scope {
			return a.Scope < b.Scope
		}
		return a.Field < b.Field
	})
	return all
}

func documents() ([]byte, []byte, error) {
	all := entries()
	data, err := json.MarshalIndent(struct {
		SchemaVersion int                        `json:"schemaVersion"`
		Scope         string                     `json:"scope"`
		Entries       []source.RegisteredFeature `json:"entries"`
	}{1, "compiler registries only; experimental, not runtime acceptance", all}, "", "  ")
	if err != nil {
		return nil, nil, err
	}
	var text bytes.Buffer
	text.WriteString("# Generated compatibility registry\n\n")
	text.WriteString("Generated by `go run ./scripts/compatibility -output docs`. Do not edit.\n\n")
	text.WriteString("These are the **compiler** registries used by the validators, not stable runtime\nsupport or an exhaustive Kubernetes/Compose field inventory. Helm-rendered\nKubernetes manifests use the same Kubernetes registry. Helm renderer preflight\nrestrictions and runtime evidence/limitations remain in [compatibility.md](compatibility.md).\n\n")
	text.WriteString("Fixture links identify regression suites, not a claim of per-field hardware coverage.\nA blank consequence means the registry supplies none; a registry without a\ndefault says so explicitly rather than inventing a Kubernetes/Compose default.\n\n")
	text.WriteString("| Format/version | Scope/field | Milestone | Compiler state | Default | Consequence | Fixtures/suites |\n| --- | --- | --- | --- | --- | --- | --- |\n")
	cell := func(s string) string {
		s = strings.ReplaceAll(s, "|", "\\|")
		return strings.ReplaceAll(s, "\n", " ")
	}
	for _, entry := range all {
		var links []string
		for _, fixture := range entry.Fixtures {
			links = append(links, fmt.Sprintf("[%s](../%s)", filepath.Base(fixture), fixture))
		}
		fmt.Fprintf(&text, "| %s / %s | %s / `%s` | %s | %s | %s | %s | %s |\n",
			cell(entry.Format), cell(entry.Version), cell(entry.Scope), cell(entry.Field), cell(entry.Milestone), entry.State,
			cell(entry.Default), cell(entry.Consequence), strings.Join(links, "; "))
	}
	return append(data, '\n'), text.Bytes(), nil
}

func main() {
	output := flag.String("output", "docs", "existing documentation output directory")
	flag.Parse()
	data, text, err := documents()
	if err == nil {
		err = os.WriteFile(filepath.Join(*output, "compatibility-registry.json"), data, 0644)
	}
	if err == nil {
		err = os.WriteFile(filepath.Join(*output, "compatibility-registry.md"), text, 0644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "compatibility generation failed:", err)
		os.Exit(1)
	}
}
