// SPDX-License-Identifier: Apache-2.0
import React, { useRef, useState } from 'react';
import { Alert, Button, Card, CardBody, Label, Tab, Tabs, TabTitleText, TextInput, Title } from '@patternfly/react-core';
import { MinusIcon, PlusIcon, TimesIcon, ExpandArrowsAltIcon } from '@patternfly/react-icons';
import { topologyModel } from './presentation.mjs';
import { bytes, safeRoute } from './client.mjs';
const list = value => Array.isArray(value) ? value : [];
const kindLabel = { route: 'Route', service: 'Service', workload: 'Workload' };

function Detail({ node, view, navigate, openExec, close }) {
  const [tab, setTab] = useState('resources');
  const item = node.data;
  const workloadIDs = node.kind === 'workload' ? [item.id] : node.kind === 'service' ? list(item.workloads) : list(view.services).find(s => s.name === item.service)?.workloads || [];
  const sandboxes = list(view.sandboxes).filter(s => workloadIDs.includes(s.workload));
  const services = node.kind === 'service' ? [item] : list(view.services).filter(s => node.kind === 'route' ? s.name === item.service : list(s.workloads).includes(item.id));
  const routes = node.kind === 'route' ? [item] : list(view.routes).filter(r => services.some(s => s.name === r.service));
  return <aside className="gr-topology-detail" aria-label="Selected resource" id="topology-detail">
    <div className="gr-detail-heading"><div><span className={`gr-kind gr-kind-${node.kind}`}>{kindLabel[node.kind].slice(0, 1)}</span><Title headingLevel="h2" size="lg">{node.name}</Title></div><Button variant="plain" aria-label="Close resource detail" onClick={close}><TimesIcon /></Button></div>
    <Tabs activeKey={tab} onSelect={(_, key) => setTab(key)} aria-label="Resource detail tabs"><Tab eventKey="details" title={<TabTitleText>Details</TabTitleText>} /><Tab eventKey="resources" title={<TabTitleText>Resources</TabTitleText>} /></Tabs>
    <div className="gr-detail-body">{tab === 'details' ? <dl className="gr-detail-list"><dt>Resource kind</dt><dd>{kindLabel[node.kind]}</dd><dt>Name</dt><dd>{node.name}</dd>{node.kind === 'workload' && <><dt>Declared replicas</dt><dd>{item.replicas}</dd><dt>Kind</dt><dd>{item.kind}</dd><dt>Container images</dt><dd>{list(item.containers).map(c => <p key={c.name}>{c.name} · <code>{c.image}</code></p>)}</dd></>}{node.kind === 'service' && <><dt>Discovery</dt><dd>{item.headless ? 'Headless' : 'ClusterIP'}</dd><dt>Declared TCP ports</dt><dd>{list(item.ports).join(', ') || 'None'}</dd></>}{node.kind === 'route' && <><dt>Declared backend</dt><dd>{item.service}</dd><dt>Endpoint</dt><dd>{safeRoute(item.endpoint) ? <a href={safeRoute(item.endpoint)} target="_blank" rel="noopener noreferrer">{item.endpoint}</a> : 'Unavailable'}</dd></>}<dt>Relationship source</dt><dd>Declared route backends and Service selectors, not traffic telemetry.</dd></dl> : <>
      <section><h3>MicroVMs <Label isCompact>{sandboxes.length}</Label></h3>{sandboxes.length ? sandboxes.slice(0, 100).map(vm => <div className="gr-resource-row" key={vm.id}><div><strong>{vm.id}</strong><p>{vm.workload} · {vm.backend}</p><p>{vm.vcpu} vCPU · {bytes(vm.guestBudgetBytes)} guest budget</p></div><Label color={vm.ready && !vm.draining ? 'green' : 'grey'} isCompact>{vm.draining ? 'Draining' : vm.ready ? 'Ready' : vm.state || 'Unavailable'}</Label><div className="gr-resource-actions"><Button variant="link" isInline onClick={() => navigate('logs')}>Daemon logs</Button>{list(vm.containers).filter(c => c.state === 'running').map(c => <Button key={c.name} variant="link" isInline onClick={() => openExec(`${vm.id}/${c.name}`)}>Exec {c.name}</Button>)}</div></div>) : <p className="gr-muted">No observed microVMs for this resource.</p>}{sandboxes.length > 100 && <p className="gr-muted">Showing the first 100 observations.</p>}</section>
      <section><h3>Services <Label isCompact>{services.length}</Label></h3>{services.map(s => <div className="gr-resource-row" key={s.name}><strong><span className="gr-kind gr-kind-service">S</span>{s.name}</strong><p>{s.headless ? 'Headless discovery' : 'ClusterIP'} · declared TCP ports {list(s.ports).join(', ') || 'none'}</p><p className="gr-muted">Selected workloads: {list(s.workloads).join(', ') || 'none'}</p></div>)}{!services.length && <p className="gr-muted">No declared Service relationship.</p>}</section>
      <section><h3>Routes <Label isCompact>{routes.length}</Label></h3>{routes.map((r, i) => <div className="gr-resource-row" key={i}><strong>{r.hostname}{r.path}</strong><p>{safeRoute(r.endpoint) ? <a href={safeRoute(r.endpoint)} target="_blank" rel="noopener noreferrer">{r.endpoint}</a> : 'Endpoint unavailable'}</p></div>)}{!routes.length && <p className="gr-muted">No declared route relationship.</p>}</section>
    </>}</div>
  </aside>;
}
export function Topology({ view, navigate, openExec }) {
  const [query, setQuery] = useState(''), [selected, setSelected] = useState(''), [zoom, setZoom] = useState(1);
  const nodeElements = useRef(new Map());
  const model = topologyModel(view, query), node = model.nodes.find(n => n.key === selected);
  function closeDetail() { nodeElements.current.get(selected)?.focus(); setSelected(''); }
  const counts = [0, 0, 0], positions = new Map(model.nodes.map(n => [n.key, { x: 35 + n.column * 310, y: 90 + counts[n.column]++ * 135 }]));
  const height = Math.max(450, Math.max(...counts) * 135 + 70);
  return <div className="gr-topology-shell">
    <div className="gr-topology-toolbar"><div><Title headingLevel="h2" size="md">Application topology</Title><span className="gr-muted">{model.nodes.length} resources · declared relationships</span></div><TextInput id="topology-search" maxLength={256} aria-label="Find topology resource by name" placeholder="Find by name…" value={query} onChange={(_, value) => { setQuery(value); setSelected(''); }} /><Button variant="secondary" isDisabled={!query} onClick={() => setQuery('')}>Clear filter</Button></div>
    {model.capped && <Alert isInline variant="info" title="Diagram limited to 100 resources per kind" />}
    <div className={`gr-topology-workspace${node ? ' gr-topology-selected' : ''}`}><div className="gr-topology-canvas"><div className={`gr-topology gr-zoom-${zoom === 1 ? 'fit' : zoom < 1 ? 'out' : 'in'}`}><svg id="topology" viewBox={`0 0 960 ${height}`} role="group" aria-label="Selectable declared Routes, Services and workload groups">
      <defs><marker id="gr-topology-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#789398" /></marker></defs>
      {['Routes', 'Services', 'Workload groups'].map((heading, i) => <text key={heading} x={35 + i * 310} y="30" className="gr-graph-heading">{heading}</text>)}
      {model.edges.map(([a, b]) => { const from = positions.get(a), to = positions.get(b); return <path key={`${a}-${b}`} className={`gr-graph-edge${selected === a || selected === b ? ' gr-edge-selected' : ''}`} markerEnd="url(#gr-topology-arrow)" d={`M${from.x + 245} ${from.y} C${from.x + 280} ${from.y},${to.x - 35} ${to.y},${to.x} ${to.y}`} />; })}
      {model.nodes.map(n => { const { x, y } = positions.get(n.key); const vms = n.kind === 'workload' ? list(view.sandboxes).filter(vm => vm.workload === n.data.id) : []; const ready = vms.filter(vm => vm.ready && !vm.draining).length; return <g key={n.key} ref={element => { if (element) nodeElements.current.set(n.key, element); else nodeElements.current.delete(n.key); }} role="button" tabIndex="0" data-kind={n.kind} aria-label={`${kindLabel[n.kind]} ${n.name}`} aria-pressed={selected === n.key} className={`gr-graph-node gr-node-${n.kind}${selected === n.key ? ' gr-node-selected' : ''}`} onClick={() => setSelected(n.key)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setSelected(n.key); } }}>
        <title>{n.name} · {kindLabel[n.kind]}</title><rect x={x} y={y - 48} width="245" height="108" rx="3" /><circle className="gr-node-ring" cx={x + 36} cy={y - 7} r="22" /><text x={x + 36} y={y - 2} textAnchor="middle" className="gr-node-symbol">{n.kind === 'workload' ? 'W' : n.kind === 'service' ? 'S' : 'R'}</text><text x={x + 70} y={y - 10} className="gr-graph-name">{n.name.length > 21 ? n.name.slice(0, 20) + '…' : n.name}</text><text x={x + 70} y={y + 11} className="gr-graph-detail">{n.kind === 'workload' ? n.data.kind : n.kind === 'service' ? n.data.headless ? 'Headless' : 'ClusterIP' : 'Published route'}</text><text x={x + 14} y={y + 42} className="gr-graph-detail">{n.kind === 'workload' ? `${ready}/${vms.length} observed VMs ready · ${n.data.replicas} desired` : n.kind === 'service' ? `${list(n.data.ports).length} TCP ports · selector inferred` : n.data.endpoint ? 'Endpoint available' : 'Endpoint unavailable'}</text>
      </g>; })}
    </svg>{!model.nodes.length && <div className="gr-topology-empty">No resources match this view.</div>}</div><div className="gr-canvas-controls"><Button variant="secondary" aria-label="Zoom out" isDisabled={zoom === 0.75} onClick={() => setZoom(0.75)}><MinusIcon /></Button><Button variant="secondary" aria-label="Zoom in" isDisabled={zoom === 1.25} onClick={() => setZoom(1.25)}><PlusIcon /></Button><Button variant="secondary" aria-label="Fit topology" onClick={() => setZoom(1)}><ExpandArrowsAltIcon /></Button><span>Routes → Services → workload groups</span></div></div>
    {node ? <Detail key={node.key} node={node} view={view} navigate={navigate} openExec={openExec} close={closeDetail} /> : <Card className="gr-topology-prompt"><CardBody><h3>Explore your application</h3><p>Select a resource to inspect its microVMs, Services and routes.</p><p>Each observed microVM is an isolation boundary. A workload group is not itself a microVM.</p><p>Connections describe declared configuration, never measured traffic.</p></CardBody></Card>}
    </div><p className="gr-topology-caption">Keyboard: Tab to a resource, Enter or Space to inspect. Filter hides unmatched resources and their edges. No traffic telemetry.</p>
  </div>;
}
